name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [12]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install and test
      run: |
        npm install
        npm test
      env:
        CI: true

  deploy-snapshot:
    needs: build
    if: github.ref == "refs/heads/master"

    steps:
      - name: Release snapshot to Clojars
        env:
          - VERSION=$(head -n 1 project.clj | cut -d' ' -f 3 | sed 's/"//g')
        run: |
          clj -Arelease --skip-tag --version $VERSION

